# Generated by Django 3.2 on 2022-04-27 14:02

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NodoPadre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Nodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('PR', 'Pregunta'), ('SO', 'Solucion')], default='PR', max_length=2)),
                ('texto', tinymce.models.HTMLField()),
                ('orden', models.IntegerField(default=0)),
                ('nodoPadre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fct.nodopadre')),
                ('nodoPadrePadre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fct.nodo')),
            ],
        ),
    ]
