# Generated by Django 3.2 on 2022-04-25 14:52

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoNodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Nodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', tinymce.models.HTMLField()),
                ('ordern', models.IntegerField(default=1)),
                ('hijo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fct.nodo')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fct.tiponodo')),
            ],
        ),
    ]
