# Generated by Django 3.2 on 2022-04-28 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fct', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nodo',
            old_name='nodoPadrePadre',
            new_name='nodoHijo',
        ),
    ]
