# Generated by Django 3.2 on 2022-04-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fct', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodo',
            name='siguiente',
            field=models.ManyToManyField(blank=True, null=True, related_name='_fct_nodo_siguiente_+', to='fct.Nodo'),
        ),
        migrations.RemoveField(
            model_name='nodo',
            name='hijo',
        ),
        migrations.AddField(
            model_name='nodo',
            name='hijo',
            field=models.ManyToManyField(blank=True, null=True, related_name='_fct_nodo_hijo_+', to='fct.Nodo'),
        ),
    ]
