# Generated by Django 3.2 on 2022-04-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fct', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodo',
            name='orden',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Orden',
        ),
    ]
