# Generated by Django 3.2 on 2022-04-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fct', '0002_rename_nodopadrepadre_nodo_nodohijo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodo',
            name='nodoHijo',
        ),
        migrations.AddField(
            model_name='nodo',
            name='nodoHijo',
            field=models.ManyToManyField(blank=True, null=True, to='fct.Nodo'),
        ),
    ]
