# Generated by Django 3.2 on 2022-04-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fct', '0002_auto_20220425_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=150)),
                ('descripcion', models.CharField(max_length=150)),
            ],
        ),
    ]
