# Generated by Django 3.2 on 2022-04-26 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fct', '0002_auto_20220426_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodo',
            name='nodoPadrePadre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fct.nodo'),
        ),
    ]
