# Generated by Django 3.2 on 2022-04-28 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fct', '0005_historia'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Historia',
            new_name='Tema',
        ),
    ]
